# -*- coding: utf-8 -*-
"""Form-Correctness-Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JSNviGuhLmDEdsw4cSFltJPWl6sEsXXU
"""

!pip install mediapipe opencv-python-headless==4.7.0.72 numpy fpdf

import cv2
import mediapipe as mp
import numpy as np
from fpdf import FPDF
from google.colab import files

mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

def calculate_angle(a, b, c):
    a = np.array(a); b = np.array(b); c = np.array(c)
    ba = a - b; bc = c - b
    denom = (np.linalg.norm(ba) * np.linalg.norm(bc))
    if denom == 0:
        return 0.0
    cosine_angle = np.dot(ba, bc) / denom
    cosine_angle = np.clip(cosine_angle, -1.0, 1.0)
    angle = np.degrees(np.arccos(cosine_angle))
    return angle

def detect_pose_and_draw(video_path, save_frames=False):
    cap = cv2.VideoCapture(video_path)
    pose = mp_pose.Pose(static_image_mode=False, min_detection_confidence=0.5, min_tracking_confidence=0.5)
    frames=[]
    angles=[]
    frame_count = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        frame_count += 1
        image_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        results = pose.process(image_rgb)

        if results.pose_landmarks:
            lm = results.pose_landmarks.landmark
            left_shoulder = [lm[11].x, lm[11].y]
            left_elbow = [lm[13].x, lm[13].y]
            left_wrist = [lm[15].x, lm[15].y]
            right_shoulder = [lm[12].x, lm[12].y]
            right_elbow = [lm[14].x, lm[14].y]
            right_wrist = [lm[16].x, lm[16].y]

            left_elbow_angle = calculate_angle(left_shoulder, left_elbow, left_wrist)
            right_elbow_angle = calculate_angle(right_shoulder, right_elbow, right_wrist)
            angles.append({'left': left_elbow_angle, 'right': right_elbow_angle})

            mp_drawing.draw_landmarks(frame, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)

            cv2.putText(frame, f"L_elbow:{int(left_elbow_angle)} R_elbow:{int(right_elbow_angle)}",
                        (10,30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0,255,0), 2)
        else:
            angles.append({'left': None, 'right': None})

        frames.append(frame)

    cap.release()
    return frames, angles

def evaluate_elbow(angle):
    if angle is None:
        return "No detection"
    if angle < 45:
        return "Too Low - incomplete"
    elif 45 <= angle <= 160:
        return "Good Rep"
    else:
        return "Too Extended"

def overlay_and_save(frames, angles, out_path="/content/output_video.mp4", fps=25):
    h, w = frames[0].shape[:2]
    writer = cv2.VideoWriter(out_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (w,h))
    for frame, a in zip(frames, angles):
        angle = a.get('left') if (a.get('left') not in (None, 0.0)) else a.get('right')
        feedback = evaluate_elbow(angle)
        cv2.putText(frame, feedback, (10, h-30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2)
        writer.write(frame)
    writer.release()
    print("Saved:", out_path)
    return out_path

from google.colab import files
uploaded = files.upload()

frames, angles = detect_pose_and_draw("sample_video.mp4")
overlay_and_save(frames, angles)

files.download("output_video.mp4")